// <auto-generated />
using System;
using Avanade.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Avanade.Migrations
{
    [DbContext(typeof(VendasContexto))]
    partial class VendasContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entity.BD.Pedido", b =>
                {
                    b.Property<int>("Id_Pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Pedido"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Data_Pedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("Telefone_Contato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Valor_Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id_Pedido");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Entity.BD.PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Pedido")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Produto")
                        .HasColumnType("integer");

                    b.Property<int?>("PedidoId_Pedido")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId_Pedido");

                    b.ToTable("PedidoItens");
                });

            modelBuilder.Entity("Entity.BD.Produto", b =>
                {
                    b.Property<int>("Id_Produto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Produto"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Data_Criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao_Produto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome_Produto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id_Produto");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Entity.BD.PedidoItem", b =>
                {
                    b.HasOne("Entity.BD.Pedido", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId_Pedido");
                });

            modelBuilder.Entity("Entity.BD.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
